ROOTDIR := ../../../../..
SUBDIRS := SourceFiles

# What we're building and where to put it

#GENERATE_EXECUTABLE := brcc

COMMONPATH := /usr/local/amdbrook/platform/brcc/src

# What to build it from




include $(ROOTDIR)/platform/utils/build/config.mk


include $(ROOTDIR)/platform/utils/build/main.mk

