ROOTDIR := ../../../..
SUBDIRS := Parser SourceFiles 

# What we're building and where to put it

#GENERATE_STATIC_OUTPUT:=HighLevelFE
#OUTPUTBASE:= /platform/brcc/bin

COMMONPATH := /usr/local/amdbrook/platform/brcc/src
         


include $(ROOTDIR)/platform/utils/build/config.mk


include $(ROOTDIR)/platform/utils/build/main.mk

